version: '2.1'

services:
  webconsole-tsg:
    build: ./
    restart: always
    mem_limit: 1g
    env_file:
      - .env
    environment:
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=0
      - BASE_URL=http://localhost
      - NODE_ENV=development
      - PORT=8083
    ports:
      - 8083:8083
